import {flushSync} from 'react-dom';
import {registerAtlasTools} from './agent-tools';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowUpRight,ChevronRight,Focus,Info,Layers3,Pause,RotateCcw,RotateCw,Search,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import AnatomyScene from './scene';
import {DEFAULT_VISIBLE,SYSTEMS,EXPLANATIONS,explanation,type AnatomySex,type Atlas,type Concept,type SceneState,type SystemId,type View} from './anatomy';
const initial:SceneState={explode:0,visible:DEFAULT_VISIBLE,selected:[],isolate:false,view:'three-quarter',rotate:false,reset:0};
const VIEW_LABELS:Record<View,string>={'three-quarter':'사선 보기','front':'정면 보기','side':'측면 보기','back':'후면 보기'};
export default function Home(){
 const [sex,setSex]=useState<AnatomySex>('male');
 const detailTitle=useRef<HTMLHeadingElement>(null);
 const [atlas,setAtlas]=useState<Atlas|null>(null),[state,setState]=useState(initial),[progress,setProgress]=useState(0),[error,setError]=useState(''),[panel,setPanel]=useState<'layers'|'search'|null>(null),[details,setDetails]=useState(false),[about,setAbout]=useState(false),[query,setQuery]=useState(''),[chosen,setChosen]=useState<Concept|null>(null);
 const defaultVisible:SystemId[]=sex==='female'?[...DEFAULT_VISIBLE,'integumentary']:DEFAULT_VISIBLE;
 useEffect(()=>{const abort=new AbortController();setProgress(0);setError('');setAtlas(null);setChosen(null);setDetails(false);setState({...initial,visible:sex==='female'?[...DEFAULT_VISIBLE,'integumentary']:DEFAULT_VISIBLE});fetch(sex==='female'?'/models/atlas-female.json':'/models/atlas.json',{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error('해부학 목록을 불러오지 못했습니다.');return r.json();}).then(data=>setAtlas(data as Atlas)).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[sex]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='/'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();setPanel('search');setDetails(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 const parts=useMemo(()=>new Map(atlas?.parts.map(p=>[p.id,p])),[atlas]);
 const counts=useMemo(()=>Object.fromEntries(SYSTEMS.map(s=>[s.id,atlas?.parts.filter(p=>p.system===s.id).length??0])),[atlas]);
 const activeSystems=SYSTEMS.filter(s=>counts[s.id]>0);
 const selectedParts=state.selected.map(id=>parts.get(id)).filter(p=>!!p),selected=selectedParts[0],system=SYSTEMS.find(s=>s.id===selected?.system);
 const visibleCount=atlas?.parts.filter(p=>state.isolate?state.selected.includes(p.id):state.visible.includes(p.system)||state.selected.includes(p.id)).length??0;
 const results=useMemo(()=>{if(!atlas)return[];const term=query.toLowerCase().trim();if(!term)return ['heart','brain','liver','stomach','spleen','pancreas','urinary bladder','trachea','uterus','ovary','vagina'].map(name=>atlas.concepts.find(c=>c.name.toLowerCase()===name)).filter((x):x is Concept=>!!x);return atlas.concepts.filter(c=>c.name.toLowerCase().includes(term)||c.id.toLowerCase().includes(term)).sort((a,b)=>a.name.length-b.name.length).slice(0,80);},[atlas,query]);
 const choose=(c:Concept)=>{setChosen(c);setState(s=>({...s,selected:c.elements,isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 useEffect(()=>{if(!atlas)return;return registerAtlasTools(atlas,c=>flushSync(()=>choose(c)));},[atlas]);
 const choosePart=(id:string)=>{const p=parts.get(id);if(!p)return;setChosen({id:p.conceptId,name:p.name,elements:[id]});setState(s=>({...s,selected:[id],isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 const toggle=(id:SystemId)=>{setDetails(false);setState(s=>({...s,selected:[],isolate:false,visible:s.visible.includes(id)?s.visible.filter(x=>x!==id):[...s.visible,id]}));};
 const reset=()=>{setState(s=>({...initial,visible:defaultVisible,reset:s.reset+1}));setChosen(null);setDetails(false);setPanel(null);};
 const openPanel=(next:'layers'|'search')=>{setDetails(false);setPanel(p=>p===next?null:next);};
 return <main className="studio">
  {atlas&&<AnatomyScene atlas={atlas} state={{...state,inspectorOpen:details&&selectedParts.length>0}} onSelect={choosePart} onProgress={n=>{setProgress(n);if(n===100)setError('');}} onError={setError}/>}
  <div className="vignette"/>
  <header className="identity"><div className="eyebrow"><span className="status-dot"/> 인터랙티브 해부학</div><h1>Human Atlas<Badge variant="outline" className="edition">3D</Badge></h1><div className="identity-meta">모델 조각 {atlas?atlas.parts.length.toLocaleString():(sex==='female'?'888':'2,234')}개 <span>·</span> {sex==='female'?'Human Reference Atlas':'BodyParts3D'}</div><div className="anatomy-choice"><Select value={sex} onValueChange={value=>{if(value==='male'||value==='female')setSex(value);}} items={[{value:'male',label:'남성 기준 모델'},{value:'female',label:'여성 기준 모델'}]}><SelectTrigger aria-label="남성 또는 여성 기준 모델 선택"><SelectValue/></SelectTrigger><SelectContent className="anatomy-choice-menu"><SelectItem value="male">남성 기준 모델</SelectItem><SelectItem value="female">여성 기준 모델</SelectItem></SelectContent></Select></div></header>
  <nav className="top-actions" aria-label="탐색 도구"><Button variant="ghost" className={panel==='search'?'active':''} onClick={()=>openPanel('search')} aria-label="해부학 구조 검색"><Search size={18}/><span>구조 검색</span><kbd>/</kbd></Button><Button variant="ghost" className="icon-button" aria-label="이 아틀라스 정보" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}><Info size={18}/></Button></nav>
  <section className={`layers-panel glass ${panel==='layers'?'mobile-open':''}`} aria-label="해부학 계통">
   <div className="panel-heading"><span>해부학 계통</span><Button variant="ghost" className="mobile-only icon-button" onClick={()=>setPanel(null)} aria-label="해부학 계통 닫기"><X size={18}/></Button><Badge variant="secondary" className="desktop-only small-number">{activeSystems.length}</Badge></div>
   <div className="layer-presets"><Button variant="ghost" aria-pressed={activeSystems.filter(x=>x.id!=='pregnancy').every(x=>state.visible.includes(x.id))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:activeSystems.map(x=>x.id).filter(x=>x!=='pregnancy')}))}>전체</Button><Button variant="ghost" aria-pressed={state.visible.length===1&&state.visible[0]==='skeletal'} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['skeletal']}))}>골격</Button><Button variant="ghost" aria-pressed={state.visible.length===6&&['cardiac','respiratory','digestive','urinary','endocrine','reproductive'].every(id=>state.visible.includes(id as SystemId))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['cardiac','respiratory','digestive','urinary','endocrine','reproductive']}))}>장기</Button></div>
   <div className="system-list">{activeSystems.map(s=><div className={`system-row ${state.visible.includes(s.id)?'enabled':''}`} key={s.id}><Button variant="ghost" className="system-name" title={`${s.name}만 표시`} onClick={()=>setState(v=>({...v,visible:[s.id],isolate:false,selected:[]}))}><span className="system-dot" style={{background:s.color}}/>{s.name}<span className="system-count">{counts[s.id]}</span></Button><Switch checked={state.visible.includes(s.id)} onCheckedChange={()=>toggle(s.id)} aria-label={`${s.name} 표시`} /></div>)}</div>
   <div className="panel-foot"><span>표시된 조각 {visibleCount.toLocaleString()}개</span><Button variant="ghost" onClick={()=>setState(s=>({...s,visible:[],selected:[],isolate:false}))}>모두 숨기기</Button></div>
  </section>
  {panel==='search'&&<section className="search-panel glass" aria-label="해부학 구조 검색"><div className="panel-heading"><span>구조 검색</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label="검색 닫기"><X size={18}/></Button></div><Combobox<Concept> items={results} value={null} onValueChange={value=>{if(value)choose(value);}} inputValue={query} onInputValueChange={setQuery} itemToStringLabel={c=>c.name} filter={null} open onOpenChange={open=>{if(!open)setPanel(null);}}><ComboboxInput autoFocus placeholder="heart, femur, cranial nerve…" aria-label="영문 해부학 명칭 또는 FMA 식별자 검색" showTrigger={false}/><ComboboxContent className="anatomy-search-results"><ComboboxEmpty>검색어와 일치하는 구조가 없습니다.</ComboboxEmpty><ComboboxList>{(c:Concept)=><ComboboxItem key={c.id} value={c}><span className="search-result-name">{c.name}</span><span className="small-number">조각 {c.elements.length}개</span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox><p className="search-note">{query?'최대 80개의 결과를 표시합니다. 더 작은 구조를 찾으려면 검색어를 구체적으로 입력하세요.':'원본 데이터의 영문 해부학 명칭 또는 FMA 식별자로 검색하세요.'}</p></section>}
  <nav className="view-controls glass" aria-label="카메라 조작">{(['three-quarter','front','side','back'] as View[]).map((v,i)=><Button variant="ghost" key={v} className={state.view===v?'active':''} aria-pressed={state.view===v} disabled={state.explode>.8&&v!=='front'} onClick={()=>setState(s=>({...s,view:v,reset:s.reset+1,rotate:false}))} title={VIEW_LABELS[v]} aria-label={VIEW_LABELS[v]}><span>{['¾','F','S','B'][i]}</span></Button>)}<i/><Button variant="ghost" disabled={state.explode>=.4} aria-label={state.rotate?'회전 일시 정지':'인체 회전'} title="자동 회전" className={state.rotate?'active':''} onClick={()=>setState(s=>({...s,rotate:!s.rotate}))}>{state.rotate?<Pause size={17}/>:<RotateCw size={18}/>}</Button><Button variant="ghost" aria-label="보기와 계통 초기화" title="초기화" onClick={reset}><RotateCcw size={17}/></Button></nav>
  <div className="scene-caption"><span className="caption-line"/><span>{state.isolate?(chosen?.name??'선택한 구조'):state.explode>.95?'해부학 구조 목록':state.explode>.05?'분리된 해부학 구조':sex==='female'?'여성 기준 참고 해부학':'성인 남성 기준 인체'}</span><span className="caption-line"/></div>
  <div className="bottom-dock glass"><Button variant="ghost" className="mobile-only dock-layers" onClick={()=>openPanel('layers')} aria-label="해부학 계통 열기"><Layers3 size={20}/><span>계통</span></Button><div className="explode-control"><div className="explode-label"><label id="explode-label">해부 구조 펼치기</label><output>{Math.round(state.explode*100)}<span>%</span></output></div><Slider aria-labelledby="explode-label" min={0} max={100} step={1} value={[state.explode*100]} onValueChange={v=>setState(s=>({...s,explode:(Array.isArray(v)?v[0]:v)/100,view:(Array.isArray(v)?v[0]:v)>80?'front':s.view,rotate:false}))}/><div className="slider-endpoints"><span>조립 상태</span><span>모든 조각</span></div></div><Button variant="ghost" className="dock-reset" onClick={reset} aria-label="조립 상태로 초기화"><RotateCcw size={18}/><span>초기화</span></Button></div>
  <footer className="studio-footer"><span>{state.explode>.8?'드래그하여 이동':'드래그하여 회전'} <b>·</b> 손가락을 벌리거나 오므려 확대·축소 <b>·</b> 탭하여 상세 보기</span><Button variant="ghost" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}>출처 및 저작자 표시 <ArrowUpRight size={12}/></Button></footer>
  {progress<100&&!error&&<div className="loading glass" role="status"><Activity size={18}/><div><strong>해부학 모델 준비 중</strong><span>{progress}% · 조각 {atlas?.parts.length.toLocaleString()??(sex==='female'?'888':'2,234')}개 불러오는 중</span><div className="loading-track"><i style={{width:`${progress}%`}}/></div></div></div>}
  {error&&<div className="loading glass error" role="alert"><p>{error}</p><Button variant="ghost" onClick={()=>location.reload()}>뷰어 다시 불러오기</Button></div>}
  <Sheet open={details&&selectedParts.length>0} modal={false} disablePointerDismissal onOpenChange={setDetails}><SheetContent initialFocus={detailTitle} className={`detail-sheet glass ${state.isolate?'is-isolated':''}`} showCloseButton={true}><div className="detail-header"><div className="detail-accent" style={{background:system?.color}}/><div className="eyebrow">{system?.name??'해부학'}</div><SheetTitle ref={detailTitle} tabIndex={-1} className="structure-title">{chosen?.name}</SheetTitle></div><div className="detail-scroll" key={`${chosen?.id}-${state.isolate}`}><SheetDescription className="structure-description">{chosen&&selected?explanation(chosen.name,selected.system):''}</SheetDescription>{chosen&&!EXPLANATIONS[chosen.name.toLowerCase()]&&<span className="context-note">계통 개요 · 원본 해부학 데이터에서 식별한 구조</span>}<div className="structure-meta"><span>아틀라스 식별자<strong>{chosen?.id}</strong></span><span>선택된 조각<strong>{state.selected.length.toLocaleString()}개</strong></span></div>{selectedParts.length>1&&<div className="member-list"><h3>포함된 구조</h3>{selectedParts.slice(0,50).map(p=><Button variant="ghost" key={p.id} onClick={()=>choosePart(p.id)}><span>{p.name}</span><ChevronRight size={14}/></Button>)}{selectedParts.length>50&&<p>모델 조각 {selectedParts.length-50}개가 더 있습니다.</p>}</div>}<a className="source-link" href={sex==='female'?'https://doi.org/10.48539/HBM352.BTSQ.586':'https://lifesciencedb.jp/bp3d/'} target="_blank" rel="noreferrer">해부학 원본 보기 <ArrowUpRight size={14}/></a></div><div className="detail-actions"><Button className={`primary-action ${state.isolate?'active':''}`} onClick={()=>setState(s=>({...s,isolate:!s.isolate,explode:0}))}><Focus size={18}/>{state.isolate?'주변 해부 구조 표시':'선택한 구조만 보기'}<ChevronRight size={16}/></Button><Button variant="ghost" className="secondary-action" onClick={()=>{setState(s=>({...s,selected:[],isolate:false}));setDetails(false);}}>선택 해제</Button></div></SheetContent></Sheet>
  <Sheet open={about} onOpenChange={setAbout}><SheetContent className="about-sheet glass"><div className="eyebrow">출처 및 범위</div><SheetTitle className="structure-title">인체의 구조를 살펴보세요.</SheetTitle><SheetDescription>남성·여성 기준의 독립적인 해부학 참고 모델을 전환해 살펴볼 수 있습니다.</SheetDescription><div className="about-copy"><p><strong>남성 · BodyParts3D</strong><br/>성인 남성 기준 해부학 모델의 개별 메시 2,234개와 명명된 개념 3,432개를 제공합니다.</p><p><strong>여성 · Human Reference Atlas</strong><br/>전신 표면, 일부 장기와 여성 생식기관을 포함한 개별 메시 888개를 제공합니다. 골격과 근육은 일부만 포함되어 있으며, 임신 참고 구조 8개는 별도 계통으로 기본 숨김 처리했습니다.</p><p>두 기준 모델은 포함 범위가 서로 다릅니다. 인체의 모든 구조나 변이를 포함하지 않으며, 하나의 명명된 개념에 여러 조각이 포함될 수 있습니다.</p><p>색상과 계통 분류는 탐색을 위해 구성했습니다. 웹에서 원활히 작동하도록 지오메트리를 단순화했으며, 짧은 설명은 일반적인 교육 정보를 제공합니다. 이 자료는 해부학 참고용이며 진단이나 수술을 위한 도구가 아닙니다.</p><h3>여성 모델 출처</h3><p>Kristen Browne and Heidi Schlehlein, Human Reference Atlas / HuBMAP, <em>3D Reference Organ Set for Female v1.5</em> (2023). CC BY 4.0. 이 뷰어에 맞게 지오메트리를 수정했습니다.</p><a href="https://doi.org/10.48539/HBM352.BTSQ.586" target="_blank" rel="noreferrer">여성 기준 데이터세트 <ArrowUpRight size={14}/></a><h3>남성 모델 출처</h3><p>BodyParts3D, © The Database Center for Life Science, CC Attribution 4.0 International 라이선스.</p><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/lic.html" target="_blank" rel="noreferrer">데이터세트 라이선스 <ArrowUpRight size={14}/></a><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html" target="_blank" rel="noreferrer">원본 지오메트리 및 메타데이터 <ArrowUpRight size={14}/></a><a href="https://academic.oup.com/nar/article/37/suppl_1/D782/1000752" target="_blank" rel="noreferrer">원문 논문 읽기 <ArrowUpRight size={14}/></a></div></SheetContent></Sheet>
 </main>;
}
